FROM golang:1.10.0-alpine
RUN apk update && apk add git && \
    go get -u github.com/golang/dep/cmd/dep && \
    go get -d github.com/DITAS-Project/VDC-Logging-Agent && \
    cd src/github.com/DITAS-Project/VDC-Logging-Agent && \
    dep ensure && \
    CGO_ENABLED=0 go build -a --installsuffix cgo --ldflags="-w -s -X main.Build=$(git rev-parse --short HEAD)" -o vdc-agent
WORKDIR src/github.com/DITAS-Project/VDC-Logging-Agent
CMD [ "sh" ]