FROM golang:1.10.1
ENV SOURCEDIR=/go/src/github.com/DITAS-Project/VDC-Logging-Agent
RUN mkdir -p ${SOURCEDIR}
WORKDIR ${SOURCEDIR}
COPY . .
RUN rm -rf vendor/ && go get -u github.com/golang/dep/cmd/dep && dep ensure
CMD ["go","test","./..."]
