FROM golang:1.10.0-alpine as vdcAgent
RUN apk update && apk add git && \
    go get -u github.com/golang/dep/cmd/dep && \
    go get -d github.com/DITAS-Project/VDC-Logging-Agent && \
    cd src/github.com/DITAS-Project/VDC-Logging-Agent && \
    dep ensure && \
    CGO_ENABLED=0 go build -a --installsuffix cgo --ldflags="-w -s -X main.Build=$(git rev-parse --short HEAD)" -o vdc-agent

FROM alpine:3.4
COPY --from=vdcAgent /go/src/github.com/DITAS-Project/VDC-Logging-Agent/vdc-agent  /vdc-agent
EXPOSE 8484
CMD [ "./vdc-agent" ]