FROM golang:1.11.5 as vdcAgent
WORKDIR /opt
COPY . .
RUN CGO_ENABLED=0 go build -a --installsuffix cgo --ldflags="-w -s -X main.Build=$(git rev-parse --short HEAD)" -o vdc-agent

FROM alpine:latest
COPY --from=vdcAgent /opt/vdc-agent  /vdc-agent
EXPOSE 8484
CMD [ "./vdc-agent" ]