swagger: '2.0'
info:
  title: VDC-Logging-Agent
  description: Monitoring and Logging agent for the DITAS SDK. 
  version: "1.0.0"
paths:
  /v1/trace:
    post:
      summary: registeres a span in zipkin or updates an exsisting one
      parameters:
        - in: body
          name: traceMessage
          schema:
            $ref: "#/definitions/TraceMessage" 
      responses:
        '200':
          description: |-
            200 response
  /v1/close:
    post:
      summary: closes a span in zipkin
      parameters:
        - in: body
          name: traceMessage
          schema:
            $ref: "#/definitions/TraceMessage" 
      responses:
        '200':
          description: |-
            200 response    
  /v1/log:
    post:
      summary: forwards a log message to elastic serach, automatilcy adding type and index information
      parameters:
        - in: body
          name: logMessage
          schema:
            $ref: "#/definitions/LogMessage" 
      responses:
        '200':
          description: |-
            200 response    
  /v1/meter:
    post:
      summary: forwards a log message to elastic serach, automatilcy adding type and index information
      parameters:
        - in: body
          name: meterMessage
          schema:
            $ref: "#/definitions/MeterMessage" 
      responses:
        '200':
          description: |-
            200 response   
definitions:
  TraceMessage:
    type: object
    properties:
        traceid:
            type: string
        parentSpanId:
            type: string
        spanId:
            type: string
        operation:
            type: string
        message:
            type: string
  MeterMessage:
    type: object
    properties:
        timestamp:
          type: string
          format: "date-time"
        value:
          type: number
          format: double
        unit:
            type: string
        kind:
          type: string
  LogMessage:
    type: object
    properties:
        timestamp:
          type: string
          format: "date-time"
        value:
          type: string